# Generated by Django 4.0.7 on 2022-08-25 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='EventProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('location', models.CharField(max_length=32)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventproviders.eventcategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventproviders.eventprovider')),
            ],
        ),
    ]
