# Generated by Django 4.0.7 on 2022-08-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventproviders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
