# Generated by Django 4.0.7 on 2022-08-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproviders', '0002_delete_event_delete_eventcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprovider',
            name='name',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
