# Generated by Django 4.0.7 on 2022-08-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventproviders', '0003_alter_eventprovider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprovider',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
