# Generated by Django 4.0.7 on 2022-08-23 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventprovider',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 12, 24, 52, 204976, tzinfo=utc), verbose_name='date registered'),
        ),
    ]
