# Generated by Django 4.0.7 on 2022-08-23 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0002_eventprovider_date_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprovider',
            name='date_reg',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
    ]
