# Generated by Django 4.0.7 on 2022-08-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0004_eventcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('location', models.CharField(max_length=32)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark.eventcategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spark.eventprovider')),
            ],
        ),
    ]
