# Generated by Django 4.0.7 on 2022-08-25 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('date_reg', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered')),
            ],
        ),
    ]
